server:
  port: 8989
  servlet:
    context-path: /quanwai/test

spring:
  datasource:
    test:
      driver-class-name: com.mysql.jdbc.Driver
      username:
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://101.132.186.98:9696?autoReconnect=true&useSSL=false&allowMultiQueries=true
    pro:
      driver-class-name: com.mysql.jdbc.Driver
      username:
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://101.132.186.98:9696?autoReconnect=true&useSSL=false
    platform:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://www.94hmj.com:3306?autoReconnect=true&useSSL=false

mybatis:
  type-aliases-package: app.entity
  mapper-locations: classpath:mapper/**/*.xml



