server:
  port: 8989
  servlet:
    context-path: /quanwai/test

spring:
  datasource:
    test:
      driver-class-name: com.mysql.jdbc.Driver
      username: HfL5a9B1
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://101.132.186.98:9696?autoReconnect=true&useSSL=false&allowMultiQueries=true
    pro:
      driver-class-name: com.mysql.jdbc.Driver
      username: aeLDGnyZ
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://101.132.186.98:9696?autoReconnect=true&useSSL=false
    platform:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 199416
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306?autoReconnect=true&useSSL=false

  resources:
    static-locations: classpath:static/**
mybatis:
  type-aliases-package: app.entity
  mapper-locations: classpath:mapper/**/*.xml


#logging:
#  level:
#    app:
#      dao: debug
